'use client';
import { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Avatar } from "@/components/ui/avatar";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useRouter } from 'next/navigation';
import { getActivePersonalityProfile } from '@/lib/services/personality';
import { generateReflection } from '@/lib/services/agent';
import { Loader2, Brain, Sparkles, Eye } from 'lucide-react';

export default function ReflectPage() {
  const router = useRouter();
  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [thoughtProcess, setThoughtProcess] = useState<string[]>([]);
  const [finalThought, setFinalThought] = useState<string | null>(null);
  const [activePersonality, setActivePersonality] = useState<any>(null);
  const [promptId, setPromptId] = useState<string | null>(null);
  const [step, setStep] = useState(1);
  const [progress, setProgress] = useState(0);
  
  // Simulate loading the active personality profile on component mount
  useState(() => {
    const loadPersonality = async () => {
      try {
        const profile = await getActivePersonalityProfile();
        setActivePersonality(profile);
      } catch (error) {
        console.error("Failed to load personality profile:", error);
      }
    };
    
    loadPersonality();
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!prompt.trim()) {
      return;
    }
    
    setIsGenerating(true);
    setProgress(10);
    setStep(2);
    
    let thoughtUpdateInterval: NodeJS.Timeout | undefined;
    
    try {
      // Simulate the thinking process with incremental updates
      thoughtUpdateInterval = setInterval(() => {
        if (progress < 90) {
          setProgress(prev => {
            const increment = Math.floor(Math.random() * 15) + 5;
            return Math.min(prev + increment, 90);
          });
        }
      }, 2000);
      
      // In a real implementation, this would be connected to the actual agent
      // Here we're simulating the thinking process
      setThoughtProcess([
        "I'm reflecting on this topic through multiple emotional perspectives...",
        "Considering the joyful and optimistic perspective...",
      ]);
      
      setTimeout(() => {
        setThoughtProcess(prev => [
          ...prev,
          "Now exploring potential concerns and cautious angles...",
        ]);
      }, 3000);
      
      setTimeout(() => {
        setThoughtProcess(prev => [
          ...prev,
          "Analyzing critical considerations and potential issues...",
        ]);
      }, 6000);
      
      // Simulate getting a response from our LangChain agent
      setTimeout(() => {
        clearInterval(thoughtUpdateInterval);
        setProgress(100);
        
        setThoughtProcess(prev => [
          ...prev,
          "Synthesizing all perspectives to form a balanced view...",
          "Finalizing reflection based on the personality profile settings..."
        ]);
        
        setFinalThought(
          `This is a simulated reflection on "${prompt}". In the actual implementation, this would be the AI's thoughtful response generated by LangChain with the personality settings applied. The reflection would show the influence of the different emotional components like Joy, Sadness, Anger, Fear, and Disgust as configured in the active personality profile.`
        );
        
        setPromptId("simulated-prompt-id-123");
        setStep(3);
        setIsGenerating(false);
      }, 8000);
      
    } catch (error) {
      if (thoughtUpdateInterval) {
        clearInterval(thoughtUpdateInterval);
      }
      console.error("Failed to generate reflection:", error);
      setIsGenerating(false);
    }
  };

  return (
    <main className="min-h-screen bg-gradient-to-b from-neutral-950 to-neutral-900 text-neutral-50">
      <div className="container mx-auto px-4 py-8">
        <Card className="mb-8 bg-neutral-800/50 border-neutral-700">
          <CardHeader>
            <CardTitle className="text-2xl">Reflection Machine</CardTitle>
            <CardDescription>
              Enter a topic and let the AI agent reflect on it
            </CardDescription>
          </CardHeader>
          <CardContent>
            {step === 1 && (
              <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                  <label htmlFor="prompt" className="block text-sm font-medium mb-2">
                    What would you like the AI to reflect on?
                  </label>
                  <Textarea
                    id="prompt"
                    placeholder="Enter a topic, question, or situation for the AI to contemplate..."
                    className="min-h-32 bg-neutral-900 border-neutral-700 text-neutral-100 placeholder:text-neutral-500"
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    disabled={isGenerating}
                  />
                </div>
                <div className="flex justify-between">
                  {activePersonality && (
                    <div className="flex items-center space-x-2">
                      <span className="text-sm text-neutral-400">Active Personality:</span>
                      <span className="text-sm font-semibold bg-neutral-700 px-2 py-1 rounded">
                        {activePersonality.name}
                      </span>
                    </div>
                  )}
                  <Button 
                    type="submit" 
                    className="bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700"
                    disabled={isGenerating || !prompt.trim()}
                  >
                    Begin Reflection
                  </Button>
                </div>
              </form>
            )}
            
            {step >= 2 && (
              <div>
                <div className="mb-6">
                  <h3 className="text-lg font-medium mb-2">Topic for Reflection</h3>
                  <div className="p-4 bg-neutral-900 rounded-lg">
                    <p className="text-neutral-200">{prompt}</p>
                  </div>
                </div>
                
                <div className="space-y-4">
                  <div className="flex items-center space-x-2 mb-2">
                    <Brain className="w-5 h-5 text-purple-400" />
                    <h3 className="text-lg font-medium">Thinking Process</h3>
                  </div>
                  
                  <div className="mb-4">
                    <div className="flex justify-between text-sm mb-1">
                      <span>Progress</span>
                      <span>{progress}%</span>
                    </div>
                    <Progress value={progress} className="h-2" />
                  </div>
                  
                  <div className="space-y-3 mb-6">
                    {thoughtProcess.map((thought, index) => (
                      <div 
                        key={index} 
                        className="flex items-start space-x-3 p-3 bg-neutral-900/50 rounded-lg animate-fadeIn"
                      >
                        <Avatar className="h-8 w-8 bg-neutral-700">
                          <span className="text-xs">AI</span>
                        </Avatar>
                        <div>
                          <p className="text-neutral-300">{thought}</p>
                        </div>
                      </div>
                    ))}
                    
                    {isGenerating && (
                      <div className="flex items-center space-x-2 text-neutral-400 p-3">
                        <Loader2 className="h-4 w-4 animate-spin" />
                        <span>Thinking...</span>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            )}
            
            {step >= 3 && finalThought && (
              <div>
                <div className="flex items-center space-x-2 mb-4">
                  <Sparkles className="w-5 h-5 text-yellow-400" />
                  <h3 className="text-lg font-medium">Final Reflection</h3>
                </div>
                
                <div className="p-4 bg-gradient-to-r from-blue-900/20 to-purple-900/20 border border-blue-800/30 rounded-lg mb-4">
                  <p className="text-neutral-100 whitespace-pre-line">{finalThought}</p>
                </div>
                
                <div className="flex items-center space-x-2 text-sm text-neutral-400">
                  <Eye className="w-4 h-4" />
                  <span>Reflection saved to your history</span>
                </div>
              </div>
            )}
          </CardContent>
          <CardFooter className="justify-between border-t border-neutral-800 pt-4">
            <Button 
              variant="outline" 
              onClick={() => router.push('/')}
              disabled={isGenerating}
            >
              Back to Home
            </Button>
            
            {step >= 3 && (
              <Button
                onClick={() => {
                  setPrompt('');
                  setThoughtProcess([]);
                  setFinalThought(null);
                  setStep(1);
                  setProgress(0);
                }}
                disabled={isGenerating}
              >
                New Reflection
              </Button>
            )}
          </CardFooter>
        </Card>
        
        {step >= 3 && (
          <Card className="bg-neutral-800/50 border-neutral-700">
            <CardHeader>
              <CardTitle className="text-xl">Personality Influence Analysis</CardTitle>
              <CardDescription>
                How each emotion contributed to this reflection
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="flex items-center">
                      <div className="w-3 h-3 rounded-full bg-yellow-500 mr-2"></div>
                      Joy
                    </span>
                    <span>45%</span>
                  </div>
                  <Progress value={45} className="h-2" />
                </div>
                
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="flex items-center">
                      <div className="w-3 h-3 rounded-full bg-blue-500 mr-2"></div>
                      Sadness
                    </span>
                    <span>15%</span>
                  </div>
                  <Progress value={15} className="h-2" />
                </div>
                
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="flex items-center">
                      <div className="w-3 h-3 rounded-full bg-red-500 mr-2"></div>
                      Anger
                    </span>
                    <span>10%</span>
                  </div>
                  <Progress value={10} className="h-2" />
                </div>
                
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="flex items-center">
                      <div className="w-3 h-3 rounded-full bg-purple-500 mr-2"></div>
                      Fear
                    </span>
                    <span>20%</span>
                  </div>
                  <Progress value={20} className="h-2" />
                </div>
                
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="flex items-center">
                      <div className="w-3 h-3 rounded-full bg-green-500 mr-2"></div>
                      Disgust
                    </span>
                    <span>10%</span>
                  </div>
                  <Progress value={10} className="h-2" />
                </div>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </main>
  );
}